[package]
name = "tenc"
version = "0.1.0"
authors = ["kfangw <kfangw@gmail.com>"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.12.4
"""

[dependencies]
cosmwasm-std = { version = "1.0.0-beta7" }
cosmwasm-storage = { version = "1.0.0-beta7" }
cw-storage-plus = "0.13.1"
cw2 = "0.13.1"
schemars = "0.8.3"
cw721-base = { version = "0.13.1", features = ["library" ] }
cw721 = { version = "0.13.1" }
cw20 = "0.13.1"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }
cw-utils = "0.13.1"
prost = "0.9.0"
cw3 = "0.13.1"
rrand = { version = "0.8.0", package="rand"}
rand_seeder = "0.2.3"
rand_pcg = "0.3.1"
rand = {path= "rand", version="0.2.0"}
[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta7" }
